### ISSUE TITLE
Only 30 users out of 100

### ISSUE THREAD

**Issue by amalkowski** [danmarsden/moodle-mod_dialogue#105] opened 2022-05-13 21:10 UTC
I noticed the problem that when the course is big (100 users) only 30 ~ are displayed in autocomplete form.

OK, I found problem:
`            promise = Ajax.call([{
                methodname: 'mod_dialogue_search_users',
                args: {
                    courseid: courseid,
                    search: query,
                    searchanywhere: true,
                    page: 0,
                    perpage: 30
                }
            }]);`

30 perpage?

**Comment by danmarsden** [comment] 2022-05-13 23:19
yes - 30 per "search" - you do know that it's a searchable selector right? - type in some text and it will filter/search for all results that match that search term (with a limit of up to 30 records in the list at a time.) - this is similar to other searchable selectors in Moodle too.

**Comment by amalkowski** [comment] 2022-05-13 23:24
Oh. You're right.

Ok

**Comment by danmarsden** [comment] 2022-06-14 01:54
closing as not a bug - thanks.

**Closed as completed by danmarsden** 2022-06-14 01:54 UTC
