### ISSUE TITLE
Dialogue name appearing twice in moodle 4.1

### ISSUE THREAD

**Issue by fabioleira** [danmarsden/moodle-mod_dialogue#127] opened 2024-01-29 14:04 UTC
Hi Dan,

I applied the fix the issue #116, But the dialogue name also appearing twice in moodle 4.1.8
I´ve remove the follow line from view.php and conversation.php files:

echo $OUTPUT->heading(format_string($activityrecord->name));

By the way, the plugin version 4.2 available on moodle repository don`t contains the bug fix  #116. When will available there? the moodle team is reviewing the code?

Thanks

**Comment by danmarsden** [comment] 2024-01-29 21:23
closing this as a duplicate of #116

@fabioleira pushing the updated code to the plugins db is mostly a manual process - I'll try to do that next time I make some changes to the codebase but in the meantime the latest version of the plugin is available here in github.

thanks!

**Closed as completed by danmarsden** 2024-01-29 21:23 UTC

**Comment by fabioleira** [comment] 2024-01-30 17:52
ok, thanks!
