### ISSUE TITLE
bulk not working in moodle 4.0

### ISSUE THREAD

**Issue by cvovolt** [danmarsden/moodle-mod_dialogue#107] opened 2022-08-06 09:55 UTC
After upgrading from Moodle 3.9 to Moodle 4.0 the dialogue plugin is unable to create bulk messages. 
Nothing happens when the 'create' button is clicked. The other conversations (not in bulk) are working fine.
Any ideas? Please let me know if I can provide more info.

**Comment by danmarsden** [comment] 2022-08-19 09:11
thanks for the report - looks like a regression caused by #104 - I've just pushed a fix into the github repository that should fix it! - let me know if you still have issues though.

**Closed as completed** 2022-08-19 09:11 UTC

**Comment by cvovolt** [comment] 2022-08-22 08:22
Thanks! That fixed it indeed.
